### ISSUE TITLE
Calendar Details (exact time and room)

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-iOS#103]
"Im Calendar wäre es gut, wenn man die genauen Zeiten sieht, sobald man auf eine Veranstaltung klickt. Oder dann vielleicht zu den Veranstaltungsinformationen weitergeleitet wird. "

**Comment by TG908** [comment]
and the room

**Comment by mathiasquintero** [comment]
Then we could listen for URL calls and intercept when someone opens a link and show it in the app

**Comment by mammuth** [comment]
Folgende User per Mail informieren:
- https://tca.exgen.io/scp/tickets.php?id=211
- https://tca.exgen.io/scp/tickets.php?id=195
- https://tca.exgen.io/scp/tickets.php?id=206

**Comment by mathiasquintero** [comment]
It would be great if we could display the room finder. However I'm having trouble finding the roomId from the calendar events location

**Comment by kordianbruck** [comment]
@mathiasquintero you will have to search for the room name and let the user chose. Thats what we do in Android. There is unfortunately no exact matching.
