### ISSUE TITLE
Configuration Profiles

### ISSUE THREAD

**Issue by tgymnich** [TUM-Dev/Campus-iOS#137]
The android app offers eduroam setup. We could do the same **(and more)** for ios with profiles.
We could offer profiles to setup:

- tum.de /mytum E-mail Account
- in.tum.de E-Mail Account
- lrz vpn on demand (automatically connects to lrz vpn when the device is in the lrz Wifi.
- eduroam Wifi: pwd configuration/encryption

**Comment by kordianbruck** [comment]
How can you login to eduroam using in.tum.de? You mean the FMI Wifi?

**Comment by TG908** [comment]
I want to create a profile that configures your in.tum.de email account. That has nothing to do with the eduroam wifi

**Comment by mathiasquintero** [comment]
@TG908 no need for a profile. NetworkExtension allows us to set up the WiFi in iOS 11

**Comment by TG908** [comment]
Great I guess we can maybe go with Personal VPN if we wanted to do the same for vpn.

**Comment by mathiasquintero** [comment]
@TG908 check this out: https://developer.apple.com/documentation/networkextension/netunnelprovidermanager

**Comment by TG908** [comment]
@mathiasquintero only supports Per-App VPN On Demand so a Profile might be better.

**Comment by mathiasquintero** [comment]
But do we really need it on demand instead of simply registering it?

**Comment by TG908** [comment]
On demand is really nice if your phone joins the lrz wifi it automatically connects to the vpn.
