### ISSUE TITLE
Chat Rooms

### ISSUE THREAD

**Issue by nerdsupremacist** [TUM-Dev/Campus-iOS#16]
Implement Chat Rooms
Probably Should go in a separate Tab.
Perhaps try to make it look like whatsapp or iMessage: 

https://github.com/jessesquires/JSQMessagesViewController
or
https://github.com/rcmcastro/whatsapp-ios

Implement after the GCM

**Comment by Husain0007** [comment]
Hello @nerdsupremacist  👋 ,
I am a first-year MS student at TUM just starting out with Swift Development. Since this issue is considered a low priority do you mind if I work on it ?
Look forward to hearing from you 😄

**Comment by kordianbruck** [comment]
Hey,

yes, feel free to start working on it. You can have a look at the android app that has a list of most of the API endpoints used for this.

Thanks!

**Comment by nerdsupremacist** [comment]
Hey! thank you so much for helping out! Go right ahead. Don't hesitate to reach out to me or to @tgymnich

**Comment by Husain0007** [comment]
@kordianbruck & @nerdsupremacist  thank you for letting me work on this issue 😄 👍  .
I'll look into the API endpoints on the Android side and try to incorporate those into my project.
I'll be sure to reach out if I run into any problems

**Comment by CommanderStorm** [comment]
As discussed in our latest Team Meetig, Android is removing the Chat via https://github.com/TUM-Dev/Campus-Android/pull/1502 in the next release.
Imo, this issue can be closed.

What do the @TUM-Dev/ios people think?

**Comment by AW-tum** [comment]
We discussed it and decided to close this issue
