### ISSUE TITLE
Evaluate removing of pod repo update from Travis

### ISSUE THREAD

**Issue by mammuth** [TUM-Dev/Campus-iOS#174]
https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming
"We are also updating this image with some changes that will improve the experience of these builds. We are adding brew update, pod repo update, and other similar updates to help speed up build times, and we are upgrading the OS X version of this image to 10.12.6 (from 10.12.5) to allow users to take advantage of newer OS X features and applications."

Does this mean we can get rid of our manual pod repo update we do?

**Comment by TG908** [comment]
no longer applicable due to app rewrite
