### ISSUE TITLE
Sort TUM.sexy redirects alphabetically

### ISSUE THREAD

**Issue by mammuth** [TUM-Dev/Campus-iOS#197]
The links should be sorted in a meaningful way, eg. alphabetically by title or by subdomain.

![image](https://user-images.githubusercontent.com/3121306/31951525-a8ff8bfa-b8de-11e7-812a-8f93e4cf3bd9.png)

**Comment by mathiasquintero** [comment]
maybe by the same categories that are on the website

**Comment by mathiasquintero** [comment]
@mammuth how long would it take you to get us the categories in the json endpoint as well?

**Comment by mammuth** [comment]
Not sure, @kordianbruck built the json endpoint. But should be easy I guess.

**Comment by mammuth** [comment]
I'll do it, gimme some time

**Comment by mathiasquintero** [comment]
@mammuth but please make it backwards compatible.
So we'll need to include the section names inside the links.

**Comment by mammuth** [comment]
True, we need to do it this way 👍 
But then it's nothing I will be able to do right now; since I'm on mobile. Simply adding the sections would have worked in the GitHub app^^

**Comment by mathiasquintero** [comment]
👍 Cool. Just ping me whenever you included this so I can update the model and UI.

I can finally use my latest function:
https://github.com/TCA-Team/iOS/blob/mathias/network-refactor/TUM%20Campus%20App/Extensions.swift#L71

**Comment by kordianbruck** [comment]
The only way to do this is to create a separate endpoint to the currently existing one. It is not extensible at the moment in tum.sexy. Would that be okay?

**Comment by mathiasquintero** [comment]
@kordianbruck that would be ok. But isn't it easier to just inject the sections a link is in during serializing into json?

If it's too complicated we can connect to a separate endpoint 😉

**Comment by kordianbruck** [comment]
@mathiasquintero nah, don't think so...

**Comment by mathiasquintero** [comment]
@kordianbruck any progress/new thoughts on this

**Comment by TG908** [comment]
done
