### ISSUE TITLE
Indicate Loading

### ISSUE THREAD

**Issue by nerdsupremacist** [TUM-Dev/Campus-iOS#211]
Right now whenever the screens are empty we display the message that there is no data available.
Perhaps we should be replacing that with Loading indicators. So we have three states:

- [ ] Data is being Loaded
- [ ] Data is there
- [ ] Data is empty

This is important for most screens so we should find a protocol extension based solution.

@TG908 Also mentioned that we should start handling the cases with no internet connection.
Perhaps with a small Pop-up like in Slack?

**Comment by mathiasquintero** [comment]
Perhaps we should also consider switching to a DataDriven + MVVM approach to defining our views. That would make our transition harder but our upkeep easier.

@TG908 @mammuth thoughts?

I know that @larryzuo would love this!

**Comment by TG908** [comment]
Sounds good but I woudn't change it until the app is stable and all the major features work.

**Comment by TG908** [comment]
no longer applicable due to app rewrite
