### ISSUE TITLE
Create Compatibility Layer for New Cards

### ISSUE THREAD

**Issue by nerdsupremacist** [TUM-Dev/Campus-iOS#212]
People Updating will already have the value of `PersistentCardOrder` set.
We have to add any new cards after the updated version is opened for the first time.

I'd suggest a json file with a 2d array. And persisting the last version of the app opened as the index in the array:

```json
[
    [ /* ids of the new cards */ ],
    [ /* ids of the new cards */ ],
    ...
]
```

**Comment by TG908** [comment]
For me adding new cards was never a problem. They would all appear in the Edit section and I can add them from there. We could just add a new badge to the edit button perhaps.

**Comment by mathiasquintero** [comment]
Exactly. You have to add them manually. 
I think that adding the new ones by default would be easier for users to understand.
You get a new feature and it's turned on by default

**Comment by TG908** [comment]
no longer applicable due to app rewrite
