### ISSUE TITLE
Include Features in Search View

### ISSUE THREAD

**Issue by nerdsupremacist** [TUM-Dev/Campus-iOS#215]
Include a "Feature" Search Category on the Search Controller.
For people who are searching for "Grades", "Lectures", "StudyRooms"

**Comment by TG908** [comment]
maybe implement a segmented control like in mail

**Comment by mathiasquintero** [comment]
I meant like listing features in the search results. But that works as well ;)

**Comment by TG908** [comment]
no longer applicable due to app rewrite
