### ISSUE TITLE
Add News Source Images

### ISSUE THREAD

**Issue by nerdsupremacist** [TUM-Dev/Campus-iOS#216]
We should probably include these beautiful images for the source of the news entry:

![News Source](https://tumcabe.in.tum.de/File/news/sources/src_5.png "News Source")

**Comment by TG908** [comment]
how does the rockte give us news

**Comment by TG908** [comment]
We should make tiny logos like these for all of our news sources:
<img width="375" alt="image 2" src="https://user-images.githubusercontent.com/7985149/32786837-4e3950e8-c955-11e7-9647-342383c6d3fd.png">

**Comment by mathiasquintero** [comment]
The backend has a list of logos already. Don't worry about making any

**Comment by TG908** [comment]
Where can I see them?

**Comment by mathiasquintero** [comment]
https://tumcabe.in.tum.de/Api/news/sources

**Comment by TG908** [comment]
@mathiasquintero you do the model I do the UI???

**Comment by mathiasquintero** [comment]
Sure. But let's get the rest of the UI redesign done before that, since this will be pretty simple

**Comment by TG908** [comment]
I don't like the existing icons. They should have more text. Nobody knows what the rocket stands for.

**Comment by TG908** [comment]
no longer applicable due to app rewrite
