### ISSUE TITLE
Kalender Sync

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-iOS#223]
"Ich wollte nur sagen, dass seit dem letzen Update mein Kalendar nicht mehr synchronisiert ist. Es werden nur die Termine für den Montag angezeigt."

https://tca.exgen.io/scp/tickets.php?id=284

**Comment by mathiasquintero** [comment]
Weird. Well we do have this little filter:

https://github.com/TCA-Team/iOS/blob/fce77c40ffa67e239ff167f95c850e97f0d2ac05/TUM%20Campus%20App/CalendarManager.swift#L41

Perhaps we're missing something

**Comment by mathiasquintero** [comment]
We should check if these problems are still there after the latest update. Even after pulling to refresh.
