### ISSUE TITLE
Calendar card

### ISSUE THREAD

**Issue by lukaskollmer** [TUM-Dev/Campus-iOS#229]
1. In the countdown, are seconds really necessary?
2. The countdown should auto-update (as of right now, it only updates on pull to refresh)
3. Date formatting should respect the device setting for 12/24h time format
(my iphone uses the 24h format, but the event start and end time are displayed in 12h format)

<br>

![img_1318](https://user-images.githubusercontent.com/6547384/33266876-8bea0d48-d377-11e7-85cf-5e89232f17e1.PNG)

**Comment by TG908** [comment]
Good points. I’ll try to implement that soon.

**Comment by mathiasquintero** [comment]
Let's try to get this fix in for the 1.4

**Comment by TG908** [comment]
no longer applicable due to app rewrite
