### ISSUE TITLE
Homework Due Date Reminders

### ISSUE THREAD

**Issue by nerdsupremacist** [TUM-Dev/Campus-iOS#233]
I always forget when I have to turn in HW.

It would be nice to have a feature where you tell it which days of the week you have to turn it in and get a notification N number of days before to do it. 
And it would turn off at the end of the semester

**Comment by TG908** [comment]
[Moodle API](https://docs.moodle.org/dev/Web_service_API_functions) we could try this...

**Comment by kordianbruck** [comment]
Moodle APIs are turned off on the TUM instance - unfortunately.

**Comment by TG908** [comment]
bummer
