### ISSUE TITLE
Rework Roomfinder

### ISSUE THREAD

**Issue by TG908** [TUM-Dev/Campus-iOS#248]
* Elastic Search: backend solr, elastic search (elk)
* Draggable/Zoomable Map
* Map to Lat/Lon => Google Map
* getMapMetric(m_id):

Returns UTM coordinates of a map plus rotation relative to the UTM grid.
(SW=southwest/lower left point, NE=northeast/upper right point)

```
Usage:
   getMapMetric(int map_id) =>[float SW_x, float SW_y, int SW_zone, float NE_x, float
NE_y, int NE_zone, float rotation]

Example:
   getMapMetric(12) =>   [690631.375, 5335887.5, 32, 691356.4375, 5336190.0, 32,
-21.271878999999998]
```

See [TumCampusApp/#777]( https://github.com/TCA-Team/TumCampusApp/issues/777)

**Comment by kordianbruck** [comment]
FYI: api will be implemented on the server and be provided with the other functions for caching reasons.

**Comment by TG908** [comment]
no longer applicable due to app rewrite
