### ISSUE TITLE
News Alerts

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-iOS#272]
We want the news alert to be shown on the top. This is a simple Image with a linkable URL and expiry date. 

https://app.tum.de/Api/news/alert/

![whatsapp image 2018-06-15 at 02 19 11](https://user-images.githubusercontent.com/298860/41642553-e643899e-7468-11e8-96de-9f0e9a0dd3bf.jpeg)

**Comment by AW-tum** [comment]
Already handled since version 4.0
