### ISSUE TITLE
Improve design of News screen

### ISSUE THREAD

**Issue by thellmund** [TUM-Dev/Campus-iOS#287]
The current design of the `NewsTableViewController` presents some potential for improvement. The current problems are: 
1. The text sizes and margins are odd.
2. TU Film movies and news items share the same cell design, even though the former has portrait images and the latter has landscape images. As a result, the news images are tiny and don’t provide any value to the user. 
3. We could potentially present the news source and its icons as on Android. 
4. We could provide a filter option as on Android. 

Items 3 and 4 are open for discussion.

**Comment by TG908** [comment]
no longer applicable due to app rewrite
