### ISSUE TITLE
Add event view in calendar

### ISSUE THREAD

**Issue by thellmund** [TUM-Dev/Campus-iOS#289]
The calendar functionality should be aligned with the Android version, namely: 
1. Allow the user to see details on a calendar event when tapping on it. This should also allow the user to open the room finder for events with a location.
2. Delete existing calendar event. 
3. Edit existing calendar event. 
4. Add new calendar event.

**Comment by kordianbruck** [comment]
This issue is too big. Please split it up. Not sure that we currenlty _can_ delete events.

**Comment by thellmund** [comment]
I will split the tasks into multiple issues. This issue was more of a brain-dump on my part.

**Comment by AW-tum** [comment]
Event info already implemented 
All Calendar Customization is handled in #239
