### ISSUE TITLE
Departures that departed more than a minute ago should be hidden

### ISSUE THREAD

**Issue by ffittschen** [TUM-Dev/Campus-iOS#312]
As a follow up from #297 and #311, I'd like to discuss hiding departures that are older than one minute.

Currently, the collection view and table view happily displays all departures, but doesn't refresh the underlying data periodically.

This results in views that show old departures if they are open for some time:
<img width="320" alt="screen shot 2018-10-17 at 10 48 25" src="https://user-images.githubusercontent.com/7734806/47074475-c01dae80-d1fa-11e8-8c85-0dfd7a37afc2.png">

I'd like to either periodically refresh the underlying data, e.g. every minute. Or there could be a smart solution that refreshes the data based on the next departure, i.e. upon loading the data, we use the earliest departure, add 60 seconds and create a one-off Timer to refresh the data at that Date.

What do you think about this idea?

**Comment by TG908** [comment]
Your idea sound good. We could also just fire a timer ever second to refresh/remove the departures.

**Comment by kordianbruck** [comment]
Yea, great idea. I like the use of the timer to hide older timer. Please just don't spam the MVV API, so they don't block us.

**Comment by TG908** [comment]
no longer applicable due to app rewrite
