### ISSUE TITLE
refreshing the study rooms list resets the selected location

### ISSUE THREAD

**Issue by lukaskollmer** [TUM-Dev/Campus-iOS#318]
Steps to reproduce:
- Open the study rooms view
- Switch to a different location
- Refresh
- Location always resets to the MI library

See [this](https://lukaskollmer.s3.amazonaws.com/campus_ios_refresh_study_rooms.mp4) screen recording

**Comment by nerdsupremacist** [comment]
Ah! Refresh sync bugs with immutable models! We meet again! Thinking about creating a library for this, but a solution is tightly coupled with the refresh architecture. Ah!!!!

**Comment by kordianbruck** [comment]
Just wondering, if there are not standard libraries for all that networking, refreshing logic? I mean we can't be the first people running into this crap.

**Comment by TG908** [comment]
happens also to cafeteria and news

**Comment by TG908** [comment]
no longer applicable due to app rewrite
