### ISSUE TITLE
Integration des TeleTeaching Tool

### ISSUE THREAD

**Issue by tumcode** [TUM-Dev/Campus-iOS#324]
Die iPad App des TeleTeachingTools wurde entwickelt, ist aber nicht mehr verfügbar, aufgrund der Lizenzgebühren des AppStores. Siehe: http://ttt.in.tum.de/

Da die TCA iOS App ohnehin existiert, kann vermutlich leicht die TTT App eingebunden werden? Dies würde die Weiternutzung des bestehenden Codes gewährleisten.

**Comment by TG908** [comment]
@kordianbruck

**Comment by TG908** [comment]
Wir können die App in TUM-Dev aufnehmen und veröffentlichen. Ich habe auf den Screenshots auf der ttt Seite gesehen, dass die App schon etwas outdated ist. Wir haben im Moment nicht genug iOS Entwickler um die App zu überarbeiten. Gibt es jemanden (im ttt team) der sich um so etwas kümmern würde?

**Comment by kordianbruck** [comment]
@tumcode wo findet sich der aktuelle quelltext denn?

**Comment by tumcode** [comment]
@kordianbruck der Quelltext findet sich auf dieser Seite: https://versioncontrolseidl.in.tum.de/petter/teleteaching-standalone/wikis/home
Dies ist der aktuelle Ansprechpartner des Projektes: http://www2.in.tum.de/hp/Main?nid=27

Ich denke das die Integration des TeleTeachingTools nochmal die Reichweite der TUMCampus App erhöhen kann, da sie noch mehr Studenten installieren, um die Funktionen des TTT nutzen zu können.

**Comment by AW-tum** [comment]
http://ttt.in.tum.de/ has not been updated since 2020 hence we will close this issue for lack of relevance
