### ISSUE TITLE
Refreshing the TU Film list also loads all news items

### ISSUE THREAD

**Issue by lukaskollmer** [TUM-Dev/Campus-iOS#325]
possibly related to #318 ?

**Comment by kordianbruck** [comment]
It should I think. @TG908 thoughts?

**Comment by lukaskollmer** [comment]
@kordianbruck to clarify, [this](https://lukaskollmer.s3.amazonaws.com/ScreenRecording_01-02-2019+22-54-41.mp4) is what i'm talking about.

IMO, the film list should always only include movie items, since it's clear that the user opened that view with the intention to see a list of movies (if they wanted to see news, they'd tap the "show all news" button)

**Comment by TG908** [comment]
Correct this is not intended. Its a bug with News/MovieManager. Im thinking of rewriting the whole app so this will get fixed eventually.

**Comment by kordianbruck** [comment]
@TG908 "the whole app" - wut

**Comment by TG908** [comment]
no longer applicable due to app rewrite
