### ISSUE TITLE
App crashing on startup

### ISSUE THREAD

**Issue by max-ae** [TUM-Dev/Campus-iOS#334]
After the 3.0 update, the app is crashing on startup.
I managed to get past the token authorization, but then the app proceeds to crash every subsequent launch.

App version 3.0
iPhone 11 Pro Max, iOS 13.5.1

**Comment by TG908** [comment]
Thank you for your feedback. We have already found the issue and submitted a new build to the appstore. In the meantime if you change your app language to English in Settings > Campus App > Language you should be able to use the app again.

**Comment by TG908** [comment]
The new beta build is available on [testflight](https://testflight.apple.com/join/AlXCNNOS)
