### ISSUE TITLE
Show which exam results are still "In Progress"

### ISSUE THREAD

**Issue by simonbohnen** [TUM-Dev/Campus-iOS#348]
Exam results can be "In Progress" or a "Valid Achievement", and possibly other states:
<img width="1155" alt="Screenshot 2020-10-31 at 17 42 57" src="https://user-images.githubusercontent.com/26229617/97784700-add3fa80-1ba0-11eb-89ea-bdc7a2964228.png">

It would be nice if these states were visible in the Grades tab.

<img width="414" alt="IMG_906CEE0114E9-1 copy" src="https://user-images.githubusercontent.com/26229617/97784833-8c274300-1ba1-11eb-8f24-8c22b1dac968.png">

There are several possibilities to do this (sorted by how well I like them):
1. Put the status of the exam result below the grade.
The information about the type of the exam result ("Schriftlich" or "Beurteilt/immanenter Prüfungscharakter") is not useful imo and could be replaced with info about the state of the result.
2. Group exam results of the last semester by status and give them a heading (Like "20S")
3. Use the dots on the left side as an indicator for the state of the exam result.
This is similar to the way it was done on the old TUMonline design, but would probably confuse users.

**Comment by tgymnich** [comment]
Thanks for the suggestion. At the moment the TUMOnline API doesn't provide this information.
cc @kordianbruck

**Comment by kordianbruck** [comment]
Hopefully we can get this with the "new API" that might come around next year or in two years. But currently I don't see how this would be possible. Closing as its really infeasible - feel free to reopen in a year. Thanks for your suggestion however, so keep em coming! :+1:

**Comment by simonbohnen** [comment]
Ah ok, that's a bummer. Is there a documentation for the TUMonline API? Couldn't find anything 🤔

**Comment by kordianbruck** [comment]
Not that I know of, but you can check the code in the app to see how it works. Its not complicated.
