### ISSUE TITLE
Add Default Campus 

### ISSUE THREAD

**Issue by mammuth** [TUM-Dev/Campus-iOS#35]
Currently there is no logic regarding the default campus I think, right @mathiasquintero?

Based on the default campus a couple of behaviours change, like the cafeteria card or the MVV card (s. #12  "Add MVV Info").

**Comment by mathiasquintero** [comment]
No there isn't any. I'd suggest just storing it somewhere in UserDefaults. Perhaps write a small wrapper for it

**Comment by TG908** [comment]
Should the user be able to select a favorite cafeteria in the same view?

**Comment by kordianbruck** [comment]
@TG908 you mean per campus? If you can sure! But I think most only have one cafeteria on a campus. No?

**Comment by TG908** [comment]
Done in #119
