### ISSUE TITLE
Exam notification

### ISSUE THREAD

**Issue by alexjoham** [TUM-Dev/Campus-iOS#350]
I've got the idea to add a notification for the registration for exams.
This notifications reminds the user to registrate themselves to the exams.

Maybe we can implement this feature using one (or both) of these two options:

1. notification by a message from the app in the notifications section of the iPhone
2. notification in the app with options to decide if you want to get reminded later or not again

_I am going to draw some sketches later._
 
I think I am going to need some time to get into the app and learn Swift/Obj C. 
It would take some time, but I am ready to work on this idea.

**Comment by tgymnich** [comment]
Great idea. For this to work we would need a way to figure out when exam registration starts or when the exams will be written.

**Comment by kordianbruck** [comment]
One idea would entail somehow anonymously reporting centrally what lectures / calendar entries people have. So as soon somebody has a "prüfung für xyz" on their calendar, we could let everyone else know that there might be the possibility of an open sign up. This would be a bit of a hack and we'd need to somehow get the calendar events on the server side, but not undoable.

**Comment by AW-tum** [comment]
#360
