### ISSUE TITLE
A little beauty scar, should be fairly easy to fix and not take long

### ISSUE THREAD

**Issue by AW-tum** [TUM-Dev/Campus-iOS#351]
copy pasted from our feedback function:

In the TUMonline-App for iPhone are no line breaks shown in in the "Additional Info"
field. Furthermore there is after a certain character limit only "…" shown, but you cannot
click on the field to view all information.

**Comment by tgymnich** [comment]
I have no idea what the "Additional Info" filed is referring to.

**Comment by AW-tum** [comment]
hmmm no idea
if he´s the only guy having this problem it might not be that important anyway
