### ISSUE TITLE
Calendar and timezone

### ISSUE THREAD

**Issue by simon300000** [TUM-Dev/Campus-iOS#352]
Seems like the calendar doesn’t support different time zones

for example, I am in China, UTC+8
Events in the calendar should be adjusted to a later time.

A different solution would be use Germany time for current time instead of the system time

iOS Version: 14.2 
App Version: 3.7 
Build Version: 40

Picture might be helpful:
![0E507031-80AA-4647-BE95-B84CDE54DB58](https://user-images.githubusercontent.com/12656264/102847438-512ce780-444d-11eb-9c6d-9f3e42020c1b.jpeg)

**Comment by tgymnich** [comment]
Thanks for letting us know. This will be fixed in version 3.8
