### ISSUE TITLE
Performanz Mensamap

### ISSUE THREAD

**Issue by ChrGrb** [TUM-Dev/Campus-iOS#358]
Beim scrollen nach oben auf dem Mensa Screen bringt die Framerate stark runter.

**Comment by tgymnich** [comment]
This should be addressed in a SwiftUI rewrite. I don't have the time to work on that right now though. But we are happy for anyone willing to contribute to a SwiftUI rewrite.

**Comment by tgymnich** [comment]
Resolved by #370
