### ISSUE TITLE
Mensa Menu Bug

### ISSUE THREAD

**Issue by ChrGrb** [TUM-Dev/Campus-iOS#361]
- Es wird bei den meisten Mensas kein Menü angezeigt. 
- Das Datum bei der Mensa Garching ist verdreht: Aktuelle MM.DD.YYYY - Sollte DD.MM.YYYY

**Comment by tgymnich** [comment]
This seems to be an issue with tum eat api: https://tum-dev.github.io/eat-api.
I can take a look at the date issue though

**Comment by tgymnich** [comment]
fixed in 62e41e7060d67d6dccfaad3e1491ff6320a2e983
