### ISSUE TITLE
SwiftUI rewrite

### ISSUE THREAD

**Issue by tgymnich** [TUM-Dev/Campus-iOS#362]

**Comment by chFlorian** [comment]
I just scrolled throught the open issues and found this one. Is there a bit more context? Do you need help with it?

**Comment by tgymnich** [comment]
Currently I don't have the time to start the rewrite for SwiftUI myself. Feel free to start with it yourself.

**Comment by chFlorian** [comment]
Alright, I'll start the rewrite then. Is iOS 13.0 still the minimum version requirement or are you planning on increasing it to 14 or 15?

**Comment by tgymnich** [comment]
Almost all of our users are at least on iOS 14 now. So feel free to bump the minimum deployment target. You even make it iOS 15 if you need to.

**Comment by chFlorian** [comment]
Sounds good! Integrating the SwiftUI Views will take a while, as I'm not experienced there. But the first View is already almost done (Lectures).

**Comment by AW-tum** [comment]
Completed in version 4.0
