### ISSUE TITLE
User Feedback: Inconsistent Profile(pictures)

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/Campus-iOS#367]
The profile you get is mostly dependent on which part of the button you click. However this behaviour is not consistently deterministic.

The black and white picture is the one I would expect as this is the picture in TUMOnline. The color picture is an old one from my ID-Card.

I tried reinstalling the app and resetting the token
Hope this information is helpful.

![image](https://user-images.githubusercontent.com/26258709/127868563-a211e386-0fca-4d72-b5b4-7bfb1c372170.jpeg)
![image](https://user-images.githubusercontent.com/26258709/127868602-7a02dd25-353c-4b2b-9c2c-ad0f4e01a3b4.jpeg)
![image](https://user-images.githubusercontent.com/26258709/127868626-77b6bf80-ffe4-46cf-8f6d-86e5482aa421.jpeg)

**Comment by tgymnich** [comment]
The core data cache right now has no real purpose. We are also having similar issues with grades for exams the user has taken multiple times.

**Comment by mvitanov** [comment]
@tgymnich Do you think it will be a good idea to store some of the API responses in cache (Profile Pic, cafeterias) and others (calendar events, lectures, grades) in some form of persistent memory (SQLite, Keychain) to avoid so many requests to TUMApi? We would introduce refreshing to allow the user to trigger the requests and update the local storage. And of course APIs like free study rooms should be triggered every time.

**Comment by tgymnich** [comment]
Some kind of cache would be nice. I don't know if using CoreData is a good idea going forward.

**Comment by AW-tum** [comment]
fixed since version 4.0
