### ISSUE TITLE
Homescreen-widget for Mensa menu 

### ISSUE THREAD

**Issue by NikolaiMadlener** [TUM-Dev/Campus-iOS#374]
Widget for home screen that displays menu of the day at the Mensa of the user's choice (or the Mensa that is nearest to the user's current location)

**Comment by tgymnich** [comment]
Great idea. Linking #85

**Comment by NikolaiMadlener** [comment]
working on it, can you assign this one to me :)?

**Comment by tgymnich** [comment]
Closed in #384
