### ISSUE TITLE
Include mensa stats into the cafeteria view

### ISSUE THREAD

**Issue by Philipp000** [TUM-Dev/Campus-iOS#375]
I've recently seen the mensa queue length tool on GitHub(https://github.com/dieliste/mensa) and would like to see it in the cafeteria view of the Campus App.

I would propose to crawl the webpage: https://mensa.liste.party/ and show the stats in the app.
I would also like to start working on this.

**Comment by tgymnich** [comment]
Sounds like a good idea. We should also consider asking / helping them to provide an API or integrate such a feature into our own API.

**Comment by Philipp000** [comment]
Okay, I will open another issue at their project, as an API would be really nice to have

**Comment by tgymnich** [comment]
For future reference https://github.com/dieliste/mensa/pull/8
