### ISSUE TITLE
Roomfinder

### ISSUE THREAD

**Issue by mvitanov** [TUM-Dev/Campus-iOS#400]

**Comment by tgymnich** [comment]
http://roomapi.tum.sexy

**Comment by tgymnich** [comment]
https://api.tum.app

**Comment by mvitanov** [comment]
Use /roomfinder/room/search to search for a room Use /roomfinder/room/coordinates to display the selected room on a map. Use /roomfinder/room/scheduleById to display a room calendar with all its events for the time. 

Discuss the usage of the API with TIM Dev

**Comment by CommanderStorm** [comment]
> http://roomapi.tum.sexy

This is outdated:
our API-Documtentation can be found here: https://editor.swagger.io/?url=https://raw.githubusercontent.com/TUM-Dev/navigatum/main/openapi.yaml

Once you are ready to switch to using us in production register on https://github.com/TUM-Dev/navigatum/issues/130 to prevent us from pushing updates without notice.

Please hit us up if you need any further help/something about our implementation does not work for you.
We are open to any feedback and would love to hear where we can improve.

Doing so would also solve https://github.com/TUM-Dev/Campus-iOS/issues/364
Related Issue on the Android side: https://github.com/TUM-Dev/Campus-Android/issues/1451
