### ISSUE TITLE
Inconsistent LectureDetails showed

### ISSUE THREAD

**Issue by mvitanov** [TUM-Dev/Campus-iOS#414]
Hey,

I found out a small bug in Lectures section. It does not always open the correct lecture from the list.
Example lecture: Introduction to Deep Learing (see video below).

The problem is related to how lecture is passed from the List to the DetailsView, since in the calendar I use only the details view and the lecture is displayed correctly.
However, there I pull the lecture by LvNr number I take from the URL, so we need to take a second look at this issue. 
Also, the UIKit implementation works as expected so it must be something with the migration that causes this.

https://user-images.githubusercontent.com/28731162/153824543-38970608-9334-4173-8bab-208fc5dcedea.mp4

**Comment by philippzagar** [comment]
Fixed by #418
