### ISSUE TITLE
Add Settings View

### ISSUE THREAD

**Issue by AW-tum** [TUM-Dev/Campus-iOS#426]

**Comment by InsanelyHarsh** [comment]
I would like to work on this task. Can you elaborate more, what is the workflow?

**Comment by 14slash12** [comment]
Hey, sorry for the late response. I started to work on this issue, but we have a lot of issues. The best would be if you could join our Discord server since we meet virtual every Thursday at 9pm in the Voice Channel (Lounge). https://discord.gg/kjcPJkYj
