### ISSUE TITLE
Implement animation/video for token management

### ISSUE THREAD

**Issue by 14slash12** [TUM-Dev/Campus-iOS#448]
In order to show how a user should enable the token if she/he is using the app for the first time it would be neat to add an animation/video.

**Comment by 14slash12** [comment]
This issue could be fixed by implementing a new video tutorial and redesigning the `TokenConfirmationView`.

![FixedToken](https://user-images.githubusercontent.com/59373377/174460087-ba081d44-f017-4007-9228-990c6855d28c.gif)

**Comment by AW-tum** [comment]
Has been implemented since version 4.0
