### ISSUE TITLE
LectureDetailView: Adding a Link to RoomfinderView when tapping on the Location of a Lecture

### ISSUE THREAD

**Issue by 14slash12** [TUM-Dev/Campus-iOS#457]
Currently the location of a lecture is just an info, but should be tappable to be redirected to the `RoomfinderView`:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/59373377/177704492-ff6ade68-fa0b-4cd6-9b6b-b1c4ce0446e9.png">

**Comment by AW-tum** [comment]
implemented since version 4.0
