### ISSUE TITLE
"Calendar days in week mode" text is shown twice

### ISSUE THREAD

**Issue by daviddiblasi** [TUM-Dev/Campus-iOS#493]
Hey, I think there is an error in Campus-iOS-swiftui-dev/Campus-iOS/ProfileComponent/View in line 96. An else or something is missing.
This results in it showing me the message "Calendar days in week mode" twice. I have iOS 16 and the newest App beta

![image](https://user-images.githubusercontent.com/92635269/191552442-7600e8e6-7c63-4126-90b4-71796d9e5206.png)

**Comment by AW-tum** [comment]
This was an issue with the iOS 16 update
