### ISSUE TITLE
Empty state for grades view

### ISSUE THREAD

**Issue by mohanadkandil** [TUM-Dev/Campus-iOS#553]
**Describe the bug**
There's an empty view for students without grades (1st semester)

**To Reproduce**
1. Go to Grades view on any platform
2. Empty white/black page

<p align="center"> 
  <img src="https://github.com/TUM-Dev/Campus-Flutter/assets/18647990/b8dfda1f-9562-40e3-b5ce-8ce381d8ac8a" alt="grades view state" width="200" />
</p>

**Expected behavior**
A clear SVG/Diagram like the one in Calendar state that "No grades until now"

<p align="center">
  <img src="https://github.com/TUM-Dev/Campus-Flutter/assets/18647990/376e0897-1eed-4795-bb9d-1e8c4fed4fd7" alt="calendar empty state" width="200" align="center" />
</p>

**Comment by jakobkoerber** [comment]
Hey, you seem to be in the wrong repository :D therefore I transfered the issue to Campus-iOS.

Could you try to install the beta via [TestFlight](https://testflight.apple.com/join/4Ddi6f2f) and test if the issue still persists? If so, please create a fork for your bugfix. We can later merge that into the repo.

**Comment by mohanadkandil** [comment]
@jakobkoerber thanks for letting me know. I am testing it now. Could you please send an invitation code for TestFlight ?

**Comment by jakobkoerber** [comment]
The code is provided via the link

**Comment by mohanadkandil** [comment]
Yeah it's an empty white/black background

<img src="https://github.com/TUM-Dev/Campus-iOS/assets/18647990/3e9afdc2-af8f-4542-8b0c-5caf3c8267ad" alt="ios-grades-view" width="300" />

**Comment by jakobkoerber** [comment]
Interesting, are you logged in? If you want to you can create a fork with the fix. Thanks for letting us know!

**Comment by mohanadkandil** [comment]
I'll start working on it. 
Can I use the same SVG for the calendar, custom one,  or what do you recommend for the grades view ?

**Comment by jakobkoerber** [comment]
please use the same

**Comment by jakobkoerber** [comment]
> **Expected behavior** A clear SVG/Diagram like the one in Calendar state that "No grades until now"
> 
> <img alt="calendar empty state" width="200" src="https://user-images.githubusercontent.com/18647990/275624329-376e0897-1eed-4795-bb9d-1e8c4fed4fd7.PNG">

Out of interest: which lectures are signed up for? We recently fixed this calendar issue, but I'm not sure if we fixed it completely. If it's fine for you it would be great to get a Token with Calendar rights from you, to take a look at the response body. 

Thanks!

**Comment by mohanadkandil** [comment]
My current courses (1st semesters - Information Engineering Heilbronn Campus):

- [Discrete Structures (INHN0004)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950698684)

- [Discrete Structures, Exercise Session (INHN0004)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950699010)

- [Introduction to Computer Organization and Technology - Computer Architecture, Exercise Session (INHN0003)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950700352)

- [Introduction to Computer Organization and Technology - Computer Architecture (INHN0003)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950700351)

- [Introduction to Informatics (INHN0001) Campus Heilbronn](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950698688)

- [Practical Course: Fundamentals of Programming (INHN0002) Campus Heilbronn](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950699642)

The problem is that the calendar is working on `iOS 16.0`; however, it's showing the mentioned error above in `17.0.3`

**Comment by jakobkoerber** [comment]
> My current courses (1st semesters - Information Engineering Heilbronn Campus):
> 
> * [Discrete Structures (INHN0004)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950698684)
> * [Discrete Structures, Exercise Session (INHN0004)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950699010)
> * [Introduction to Computer Organization and Technology - Computer Architecture, Exercise Session (INHN0003)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950700352)
> * [Introduction to Computer Organization and Technology - Computer Architecture (INHN0003)](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950700351)
> * [Introduction to Informatics (INHN0001) Campus Heilbronn](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950698688)
> * [Practical Course: Fundamentals of Programming (INHN0002) Campus Heilbronn](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950699642)
> 
> The problem is that the calendar is working on `iOS 16.0`; however, it's showing the mentioned error above in `17.0.3`

Wait, so you have a device with a working calendar and one without one? And they are running different versions of iOS?

**Comment by mohanadkandil** [comment]
Yes. 17.0.3 is not working. 16.0 device is working well

**Comment by mohanadkandil** [comment]
I have a list of the active tokens on TUM website, so how to get the actual token to see the response ?

**Comment by jakobkoerber** [comment]
> Yes. 17.0.3 is not working. 16.0 device is working well

Really interesting... could you do me a favour and install TestFlight on the `17.0.3` device and install the latest version of the Campus-App. Should be `4.2 Build 56`. And welcome to TUM by the way!

**Comment by jakobkoerber** [comment]
> I have a list of the active tokens on TUM website, so how to get the actual token to see the response ?

You cannot directly from the website, you can either give me your TUM ID via Email or Discord and give the token only rights for the calendar or you read out the token yourself in Xcode with a respective print statement. It would be really helpful for us to see a response body but I would totally understand if you have privacy concerns regarding that :)

**Comment by mohanadkandil** [comment]
> > I have a list of the active tokens on TUM website, so how to get the actual token to see the response ?
> 
> You cannot directly from the website, you can either give me your TUM ID via Email or Discord and give the token only rights for the calendar or you read out the token yourself in Xcode with a respective print statement. It would be really helpful for us to see a response body but I would totally understand if you have privacy concerns regarding that :) You can also create the response body yourself and send me that

No privacy concerns. Just send your discord handle

**Comment by mohanadkandil** [comment]
> > Yes. 17.0.3 is not working. 16.0 device is working well
> 
> Really interesting... could you do me a favour and install TestFlight on the `17.0.3` device and install the latest version of the Campus-App. Should be `4.2 Build 56`. And welcome to TUM by the way!

The one with TestFlight is the device with version 17.0.3

**Comment by jakobkoerber** [comment]
> No privacy concerns. Just send your discord handle

japauko

**Comment by jakobkoerber** [comment]
> The one with TestFlight is the device with version 17.0.3

Running 4.2 (56)? 😵

**Comment by mohanadkandil** [comment]
> > The one with TestFlight is the device with version 17.0.3
> 
> Running 4.2 (56)? 😵

unfortunately yes
