### ISSUE TITLE
Calender: month overview

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-iOS#71]
User Feedback: "Eine Monatsübersicht wäre sehr nützlich "

**Comment by kordianbruck** [comment]
> Es wäre sehr hilfreich wenn der Kalender auch eine Wochen/ Monatsansicht zur Verfügung stellen würde oder man die Termine in seinen Kalender auf dem iPhone importieren kann.

**Comment by TG908** [comment]
Maybe use another library...

**Comment by tgymnich** [comment]
This Library might be a good choice: https://github.com/kvyatkovskys/KVKCalendar
