### ISSUE TITLE
Alarm / notification system

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-iOS#9]
It would be great to have GCM on the iOS app as well in order to be able to support the Alarm feature on both platforms and maybe get better backing from the TUM through this.

The GCM message format is listed here: https://github.com/TCA-Team/TumCampusApp/wiki/GCM-Message-format

The GCM message does not contain all the information needed as that would probably exceed the size limit of the GCM payload. In order to fetch the full message please check the API client in the Android version.

![screenshot_2015-11-05-18-20-03](https://cloud.githubusercontent.com/assets/298860/12826624/32c04ec6-cb7c-11e5-96b6-adaaf3d52cbe.png)
![screenshot_2015-11-05-18-14-23](https://cloud.githubusercontent.com/assets/298860/12826625/32c1dc96-cb7c-11e5-9f5a-05315cfb9880.png)

**Comment by pfent** [comment]
GCM on iOS can probably be implemented via https://developers.google.com/cloud-messaging/ios/client?ver=swift

**Comment by mathiasquintero** [comment]
Thanks!
I will start working on this right after the exams.
I'm still kind of fussy on the architecture of this thing and what role the TumCabe Backend plays in this and what is handled by Google.
I soon as I've read all of this, who should I go to for questions? @kordianbruck ?

**Comment by kordianbruck** [comment]
The TumCabe backend holds the full information on the notification (e.g.: description text for the alarm). GCM is only there to initiate the connection and let the client know that there is new information to fetch. This saves battery power, as we do not have to deal with setup a long lived socket and MQTT ourselfs (Message queue).

Yea, ask me any time - I can give you all infos ;)

**Comment by mammuth** [comment]
Depends on https://github.com/TCA-Team/backend/issues/2

**Comment by kordianbruck** [comment]
The issue referenced above, is already done. It was about migrating to Firebase, which we have completed. 
Anyone willing to implement this, please contact me, in order to get the proper certificates for the GCM push messages.

**Comment by TG908** [comment]
Have you set [this](https://firebase.google.com/docs/cloud-messaging/ios/certs) up

**Comment by kordianbruck** [comment]
yes, I think @mammuth worked on this already and pretty much finish it.

**Comment by mathiasquintero** [comment]
The preliminary feature needs to be implemented for 1.3.1. 
Will only support the Alarm Payload and add chat later.
Updates should be handled differently I guess since the payload appears to be only available for Android and the App Store Updates are pretty fast due to autoupdate

**Comment by mathiasquintero** [comment]
@mammuth can you please push anything you have on this?
@TG908 do you wanna take this one, or should I? I don't know how you're doing on time

**Comment by TG908** [comment]
Feel free to take this one. I’m still I’m my exam phase.

**Comment by mammuth** [comment]
Same :disappointed:

**Comment by mammuth** [comment]
Same :disappointed:

@mathiasquintero I once checked out firebase and started creating the needed certs and profiles and tinkered around with some code snippets in the app but there is nothing that could be pushed I think.

**Comment by AW-tum** [comment]
Will be handled in https://github.com/TUM-Dev/Campus-iOS/issues/360
