### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by TG908** [TUM-Dev/Campus-iOS#95]
At this point we should think about localizing our app because it is a mix of german and english at the moment. We should at least feature german and english. Maybe we can get the TUM Language Cafe involved, and translate the app in some more languages. We could just print some templates and leave them at the tables to be translated.

How is localization handled in the android app?

**Comment by kordianbruck** [comment]
Android: natively from the SDK supports translation of all strings via an .XML file. (Strings.xml)

**Comment by TG908** [comment]
Do we have any translated strings files?

**Comment by kordianbruck** [comment]
Yes, you just need to check the different Values folders: https://github.com/TCA-Team/TumCampusApp/tree/master/app/src/main/res
(values-de/ru/fr/es/it)

**Comment by TG908** [comment]
no longer applicable due to app rewrite
